# ╔────────────────────────────────────────────────────────────────────────────╗
# │  ___    ___ ________  ________  ________  ________  _______   ________     │
# │ |\  \  /  /|\   __  \|\   __  \|\   __  \|\   ___ \|\  ___ \ |\   __  \    │
# │ \ \  \/  / | \  \|\ /\ \  \|\  \ \  \|\  \ \  \_|\ \ \   __/|\ \  \|\  \   │
# │  \ \    / / \ \   __  \ \  \\\  \ \   _  _\ \  \ \\ \ \  \_|/_\ \   _  _\  │
# │   \/  /  /   \ \  \|\  \ \  \\\  \ \  \\  \\ \  \_\\ \ \  \_|\ \ \  \\  \| │
# │ __/  / /      \ \_______\ \_______\ \__\\ _\\ \_______\ \_______\ \__\\ _\ │
# │|\___/ /        \|_______|\|_______|\|__|\|__|\|_______|\|_______|\|__|\|__|│
# │\|___|/                                                                     │
# ╚────────────────────────────────────────────────────────────────────────────╝

# yBorder v1.1.0

#  CREATOR INFO AND CONTACT METHODS

# Developer: yLabui
# Github: https://github.com/rchGustavo
# Discord: labui
# Contact: ylabui.contact@gmail.com
# YouTube: https://www.youtube.com/@yLabuiDev
# My Discord server: https://discord.gg/huWzxKd8M2


#  PLUGIN CONFIGURATION

#  Here you define the permission required to be able to use all plugin commands.
# Keep in mind that server operators do not need the permission, only regular
# non-OP players will require it.

admin-permission: "border.admin"


#  Do not modify anything below. This section is used to save
# the barriers that were created, storing the world and the size
# of the borders. If the server is shut down or restarted, they
# will remain saved here. To create barriers, use only the in-game commands!

barrier:
  world:
    size:


#  Below you can define custom messages for different situations.
# Modify them as you wish and, in case of another language,
# you can simply translate the texts. Only change the parts
# inside the double quotes.

messages:
  # Errors and permissions
  not_permission: "&cBorder: Only OPERATORS can execute this command."
  invalid_usage: "&cBorder: Incorrect command usage. Check the syntax."
  invalid_size: "&cBorder: Invalid size! Please enter a valid value."
  invalid_format_time: "&cBorder: Invalid time format."
  invalid_number_time: "&cBorder: Invalid number in time."
  invalid_unit_time: "&cBorder: Invalid time unit. Use s, m, h, or d."
  invalid_time: "&cBorder: Invalid time."

  # Edge States
  world_have_border: "&cBorder: This world already has a defined border! Use /border update <new_value> to change it."
  world_not_have_border: "&cBorder: This world currently has no active border."
  not_border_found: "&cBorder: No active border found in this world."

  # Actions taken
  border_set: "&aBorder: Border set to size &e%size%&a."
  border_update: "&aBorder: Border updated! New size: &e%size%&a."
  border_removed: "&cBorder: Border successfully removed."
  border_removed_timed: "&cThe Border will be removed in: &e%time%&c."
  border_removed_title: "§bThe Border"
  border_removed_subtitle: "&cHas been removed"
  border_enter: "&cBorder: You cannot cross the world boundaries!"
  border_list: "&aWorld: &e%world% &a| Border size: &e%size%"
  reload_sucess: "&aBorder: Configurations successfully reloaded!"

  # Time Units
  day_unit: "Day"
  hour_unit: "Hour"
  minute_unit: "Minute"
  second_unit: "Second"
